"""space table

Revision ID: 0b3a9f0cb1e0
Revises: c7d46a278a19
Create Date: 2024-03-21 12:41:15.329789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3a9f0cb1e0'
down_revision = 'c7d46a278a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_number', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['street_id'], ['street.street_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_number')
    )
    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_space_street_id'), ['street_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_space_street_id'))

    op.drop_table('space')
    # ### end Alembic commands ###
