"""created all tables

Revision ID: 8fd9193e260a
Revises: 
Create Date: 2024-03-22 01:44:46.631731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd9193e260a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=64), nullable=False),
    sa.Column('vendor_email', sa.String(length=64), nullable=False),
    sa.Column('street_name', sa.String(length=64), nullable=False),
    sa.Column('space_number', sa.Integer(), nullable=False),
    sa.Column('about_business', sa.String(length=140), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permit_space_number'), ['space_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_permit_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_permit_street_name'), ['street_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_permit_vendor_email'), ['vendor_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_permit_vendor_name'), ['vendor_name'], unique=False)

    op.create_table('street',
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('street_id')
    )
    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_street_street_name'), ['street_name'], unique=True)

    op.create_table('space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_number', sa.Integer(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['street_id'], ['street.street_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_space_space_number'), ['space_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_space_street_id'), ['street_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_space_street_id'))
        batch_op.drop_index(batch_op.f('ix_space_space_number'))

    op.drop_table('space')
    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_street_street_name'))

    op.drop_table('street')
    with op.batch_alter_table('permit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permit_vendor_name'))
        batch_op.drop_index(batch_op.f('ix_permit_vendor_email'))
        batch_op.drop_index(batch_op.f('ix_permit_street_name'))
        batch_op.drop_index(batch_op.f('ix_permit_status'))
        batch_op.drop_index(batch_op.f('ix_permit_space_number'))

    op.drop_table('permit')
    # ### end Alembic commands ###
