"""street table

Revision ID: c7d46a278a19
Revises: 
Create Date: 2024-03-21 11:42:28.458977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d46a278a19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('street',
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('street_id')
    )
    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_street_street_name'), ['street_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('street', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_street_street_name'))

    op.drop_table('street')
    # ### end Alembic commands ###
